right_format = """
$memory_usage\
$battery\
$cmd_duration\
$time
"""

format = "$all"

[aws]
disabled = true

[battery]
discharging_symbol = "⚡"

[[battery.display]]
threshold = 100 
style = "bold red"

[character]
error_symbol = "[✗](bold red) "

[directory]
truncation_length = 5

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[package]
disabled = true

[status]
disabled = false

[time]
disabled = false
style = "bold green"

[username]
show_always = false 
